spring:
  config:
    import: "configserver:${CONFIG_SERVER_URI}"
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME} # 配置中心的認證用戶名
      password: ${CONFIG_SERVER_PASSWORD} # 配置中心的認證密碼
      fail-fast: true # 啟動時若無法連接配置中心，則立即失敗
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}